### ISSUE TITLE
inconsistent input file

### ISSUE THREAD

**Issue by aremazeilles** [AdrianaTorres/Irregular_Terrains#15]
In the spirit of #14, I was looking at the input files:

Looking at `Margin_Stability_octave/tests/data/input/gaitEvents_plano01.csv`:

```term
╭─anthony@PRT0962AL ~/code/eurobench/csic/pi_irregular ‹fix_output_name*› 
╰─$ more Margin_Stability_octave/tests/data/input/gaitEvents_plano01.csv      
r_heel_strike;l_heel_strike;r_toe_off;l_toe_off
458,406
568,509
675,621
,,520,464
,,631,574
```

The file is ill-constructed.

We would expect something like the following:

```csv
r_heel_strike;l_heel_strike;r_toe_off;l_toe_off
458.406; 568,509; 675.621; 520,464
```
I am not sure whether the `, ` is a float mark or a value delimiter. But still the input file content should be revised.

**Comment by AdrianaTorres** [comment]
The comma here is a delimiter. That is the reason why the last two rows start with ", ,", because the first three rows have the values for the right and left heel strike (which are the first two columns) and the fourth and fifth rows have the values for the left and right toe off (which are the last two columns). The format you proposed does not fit the data because what we have is three values for right and left heel strike and two for right and left toe off (these values are the frame in which these events occur, that why there are many values for each label).

**Comment by aremazeilles** [comment]
See suggestion in #16
